Final new features and the v1.2.0 release

diff --git a/mkrelease b/mkrelease
--- a/mkrelease
+++ b/mkrelease
@@ -1,5 +1,10 @@
 #!/bin/bash -x
 ./runtests
+if [ $? -ne 0 ]
+then
+    echo "Tests failed! Stopping release!"
+    exit $?
+fi
 version=$1
 echo $version >VERSION
 echo "__version__ = '$version'" >ped_core/version.py
